<?php

namespace SuperV\Platform\Support;

use SuperV\Platform\Domains\Droplet\Port\Port;

class UrlGenerator extends \Illuminate\Routing\UrlGenerator
{

   public function to($path, $extra = [], $secure = null)
   {
       if ($prefix = app(Port::class)->getPrefix()) {
           $path = $prefix . '/' . $path;
       }
       return parent::to($path, $extra, $secure); // TODO: Change the autogenerated stub
   }
}