<?php

namespace SuperV\Platform\Domains\Droplet;

use SuperV\Platform\Domains\Entry\EntryModel;
use SuperV\Platform\Domains\Entry\EntryObserver;

class DropletObserver extends EntryObserver
{
    public function updating(EntryModel $entry)
    {
        parent::updating($entry); // TODO: Change the autogenerated stub
    }
}